(() => {
  const GUEST_KEY = 'focusGuestMode';
  const SYNC_KEYS = ['todos', 'focusSessions', 'focusPresets', 'sceneState', 'bgScene', 'focusTimerState', 'focusDisplayName'];
  const configured = Boolean(window.FOCUS_SUPABASE_URL && window.FOCUS_SUPABASE_PUBLISHABLE_KEY);
  let client, user, lastSignature = '';
  const api = { get user() { return user; }, syncNow: () => syncNow(), signOut: () => signOut(), ready: null, configured };
  window.FocusAccount = api;
  const snapshot = () => Object.fromEntries(SYNC_KEYS.map(k => [k, localStorage.getItem(k)]).filter(([,v]) => v !== null));
  const setSnapshot = data => Object.entries(data || {}).forEach(([k,v]) => { if (SYNC_KEYS.includes(k) && typeof v === 'string') localStorage.setItem(k, v); });
  function merge(local, remote) { try { const a = JSON.parse(local), b = JSON.parse(remote); if (Array.isArray(a) && Array.isArray(b)) { const seen = new Set(); return JSON.stringify([...b, ...a].filter(x => { const id = x && typeof x === 'object' ? (x.id || x.timestamp || JSON.stringify(x)) : JSON.stringify(x); if (seen.has(id)) return false; seen.add(id); return true; })); } } catch (_) {} return local || remote; }
  async function syncNow() { if (!user || !navigator.onLine) return; const data = snapshot(), next = JSON.stringify(data); if (next === lastSignature) return; const { error } = await client.from('focus_user_snapshots').upsert({ user_id:user.id, data, updated_at:new Date().toISOString() }); if (!error) lastSignature = next; }
  async function loadAndMerge() { if (!localStorage.getItem('focusDisplayName') && user.user_metadata?.display_name) localStorage.setItem('focusDisplayName', user.user_metadata.display_name); const local = snapshot(); const { data } = await client.from('focus_user_snapshots').select('data').eq('user_id',user.id).maybeSingle(); if (data?.data) { const joined = {...data.data}; SYNC_KEYS.forEach(k => joined[k] = merge(local[k], data.data[k])); setSnapshot(joined); } lastSignature = ''; await syncNow(); }
  function accountButton() { let b = document.querySelector('#focus-account-button'); if (!b) { b=document.createElement('button'); b.id='focus-account-button'; b.style.cssText='position:fixed;right:16px;bottom:16px;z-index:9998;border:1px solid #ffffff66;border-radius:999px;padding:9px 13px;background:#101820d9;color:#fff;font:600 13px system-ui;cursor:pointer;backdrop-filter:blur(12px)'; document.body.append(b); } b.textContent = user ? 'Profile' : 'Sign in'; b.onclick = () => location.assign(user ? 'profile.html' : 'login.html'); }
  async function signOut() { if (client) await client.auth.signOut(); user = null; localStorage.setItem(GUEST_KEY,'1'); accountButton(); }
  async function finish(session) { user = session?.user || null; if (user) { localStorage.removeItem(GUEST_KEY); await loadAndMerge(); } accountButton(); window.dispatchEvent(new CustomEvent('focus-account-ready',{detail:{user}})); }
  async function start() { if (!configured || !window.supabase) { accountButton(); window.dispatchEvent(new CustomEvent('focus-account-ready',{detail:{user:null}})); return; } client = window.supabase.createClient(window.FOCUS_SUPABASE_URL,window.FOCUS_SUPABASE_PUBLISHABLE_KEY); const {data:{session}} = await client.auth.getSession(); if (!session && !localStorage.getItem(GUEST_KEY)) { const page = location.pathname.split('/').pop() || 'index.html'; location.replace(`login.html?return=${encodeURIComponent(page)}`); return; } await finish(session); client.auth.onAuthStateChange((_event,session) => setTimeout(() => finish(session),0)); setInterval(syncNow,5000); window.addEventListener('online',syncNow); }
  api.ready = start();
})();
