(() => {
  const GUEST_KEY = 'focusGuestMode';
  const SYNC_KEYS = ['todos', 'focusSessions', 'focusPresets', 'sceneState', 'bgScene', 'focusTimerState', 'focusDisplayName'];
  const configured = Boolean(window.FOCUS_SUPABASE_URL && window.FOCUS_SUPABASE_PUBLISHABLE_KEY);
  let client, user, lastSignature = '';
  const api = { get user() { return user; }, syncNow: () => syncNow(), signOut: () => signOut(), ready: null };
  window.FocusAccount = api;

  const style = document.createElement('style');
  style.textContent = `#focus-account-button{position:fixed;right:16px;bottom:16px;z-index:9998;border:1px solid #ffffff66;border-radius:999px;padding:9px 13px;background:#101820d9;color:#fff;font:600 13px system-ui;cursor:pointer;backdrop-filter:blur(12px)}#focus-account-overlay{position:fixed;inset:0;z-index:9999;display:grid;place-items:center;padding:20px;background:#071018b8;backdrop-filter:blur(10px);font-family:system-ui,sans-serif}#focus-account-card{width:min(100%,400px);padding:28px;border:1px solid #ffffff38;border-radius:20px;background:#101820;color:#fff;box-shadow:0 20px 60px #0008;text-align:center}#focus-account-card h2{margin:0 0 9px;font-size:24px}#focus-account-card p{margin:0 0 20px;color:#c7d4dd;line-height:1.5;font-size:14px}#focus-account-card input{width:100%;margin:6px 0;padding:12px;border:1px solid #ffffff33;border-radius:10px;background:#ffffff12;color:#fff;font:inherit}#focus-account-card button{width:100%;margin-top:9px;padding:12px;border:0;border-radius:10px;background:#76d5ff;color:#062030;font:700 14px system-ui;cursor:pointer}#focus-account-card button.secondary{background:#ffffff16;color:#fff}#focus-account-card button.google{background:#fff;color:#24292f}#focus-account-card button.link{background:none;color:#9fdcff;padding:6px}.focus-account-note{min-height:18px;margin-top:12px!important;color:#ffcf86!important}.focus-divider{display:flex;align-items:center;gap:10px;margin:15px 0;color:#9eb0bc;font-size:12px}.focus-divider:before,.focus-divider:after{content:'';height:1px;flex:1;background:#ffffff24}`;
  document.head.append(style);

  const snapshot = () => Object.fromEntries(SYNC_KEYS.map(key => [key, localStorage.getItem(key)]).filter(([, value]) => value !== null));
  const signature = () => JSON.stringify(snapshot());
  const setSnapshot = data => Object.entries(data || {}).forEach(([key, value]) => { if (SYNC_KEYS.includes(key) && typeof value === 'string') localStorage.setItem(key, value); });
  function merge(local, remote) { try { const a = JSON.parse(local), b = JSON.parse(remote); if (Array.isArray(a) && Array.isArray(b)) { const seen = new Set(); return JSON.stringify([...b, ...a].filter(x => { const id = x && typeof x === 'object' ? (x.id || x.timestamp || JSON.stringify(x)) : JSON.stringify(x); if (seen.has(id)) return false; seen.add(id); return true; })); } } catch (_) {} return local || remote; }
  async function syncNow() { if (!user || !navigator.onLine) return; const data = snapshot(), next = JSON.stringify(data); if (next === lastSignature) return; const { error } = await client.from('focus_user_snapshots').upsert({ user_id: user.id, data, updated_at: new Date().toISOString() }); if (!error) lastSignature = next; }
  async function loadAndMerge() { if (!localStorage.getItem('focusDisplayName') && user.user_metadata?.display_name) localStorage.setItem('focusDisplayName', user.user_metadata.display_name); const local = snapshot(); const { data } = await client.from('focus_user_snapshots').select('data').eq('user_id', user.id).maybeSingle(); if (data?.data) { const joined = { ...data.data }; SYNC_KEYS.forEach(key => joined[key] = merge(local[key], data.data[key])); setSnapshot(joined); } lastSignature = ''; await syncNow(); }
  const removeOverlay = () => document.querySelector('#focus-account-overlay')?.remove();
  function accountButton() { let button = document.querySelector('#focus-account-button'); if (!button) { button = document.createElement('button'); button.id = 'focus-account-button'; document.body.append(button); } button.textContent = user ? 'Profile' : 'Account'; button.onclick = () => user ? location.assign('profile.html') : showAccount('choice'); }
  async function signOut() { if (client) await client.auth.signOut(); user = null; localStorage.setItem(GUEST_KEY, '1'); accountButton(); }
  async function googleLogin(note) { if (!configured) { note.textContent = 'Add Supabase details to supabase-config.js first.'; return; } const { error } = await client.auth.signInWithOAuth({ provider: 'google', options: { redirectTo: new URL('profile.html', location.href).href } }); if (error) note.textContent = error.message; }
  function showAccount(mode = 'choice') {
    removeOverlay(); const overlay = document.createElement('div'); overlay.id = 'focus-account-overlay'; const card = document.createElement('div'); card.id = 'focus-account-card'; overlay.append(card); document.body.append(overlay);
    const close = () => { removeOverlay(); accountButton(); };
    if (mode === 'form') {
      card.innerHTML = `<h2>Welcome back</h2><p>Sign in to safely sync FOCUS across your devices.</p><input id="focus-name" placeholder="Your name (new accounts)" autocomplete="name"><input id="focus-email" type="email" placeholder="Email" autocomplete="email"><input id="focus-password" type="password" placeholder="Password" autocomplete="current-password"><button id="focus-login">Sign in</button><button class="secondary" id="focus-signup">Create account</button><div class="focus-divider">or</div><button class="google" id="focus-google">Continue with Google</button><button class="link" id="focus-back">Back</button><p class="focus-account-note" id="focus-note"></p>`;
      const note = card.querySelector('#focus-note'); const disabled = !configured; if (disabled) note.textContent = 'Add Supabase details to supabase-config.js first.';
      const creds = () => ({ email: card.querySelector('#focus-email').value.trim(), password: card.querySelector('#focus-password').value });
      card.querySelector('#focus-login').onclick = async () => { if (disabled) return; const { error } = await client.auth.signInWithPassword(creds()); note.textContent = error ? error.message : 'Signed in.'; };
      card.querySelector('#focus-signup').onclick = async () => { if (disabled) return; const name = card.querySelector('#focus-name').value.trim(); const { error } = await client.auth.signUp({ ...creds(), options: { data: { display_name: name } } }); note.textContent = error ? error.message : 'Check your email to confirm your account.'; };
      card.querySelector('#focus-google').onclick = () => googleLogin(note); card.querySelector('#focus-back').onclick = () => showAccount(); return;
    }
    card.innerHTML = `<h2>Welcome to FOCUS</h2><p>Continue privately on this device, or sign in to keep your focus data synced everywhere.</p><button id="focus-guest">Continue without an account</button><button class="secondary" id="focus-account">Sign in or create account</button>`;
    card.querySelector('#focus-guest').onclick = () => { localStorage.setItem(GUEST_KEY, '1'); close(); }; card.querySelector('#focus-account').onclick = () => showAccount('form');
  }
  async function onSession(session) { user = session?.user || null; if (user) { localStorage.removeItem(GUEST_KEY); removeOverlay(); await loadAndMerge(); } else if (!localStorage.getItem(GUEST_KEY)) showAccount(); accountButton(); window.dispatchEvent(new CustomEvent('focus-account-ready', { detail: { user } })); }
  async function start() { if (!configured || !window.supabase) { if (!localStorage.getItem(GUEST_KEY)) showAccount(); accountButton(); window.dispatchEvent(new CustomEvent('focus-account-ready', { detail: { user: null } })); return; } client = window.supabase.createClient(window.FOCUS_SUPABASE_URL, window.FOCUS_SUPABASE_PUBLISHABLE_KEY); const { data: { session } } = await client.auth.getSession(); await onSession(session); client.auth.onAuthStateChange((_event, session) => setTimeout(() => onSession(session), 0)); setInterval(syncNow, 5000); window.addEventListener('online', syncNow); }
  api.ready = start();
})();
