(() => {
  const note = document.querySelector('#note'); let mode = 'signin'; const configured = Boolean(window.FOCUS_SUPABASE_URL && window.FOCUS_SUPABASE_PUBLISHABLE_KEY); const returnTo = new URLSearchParams(location.search).get('return') || 'index.html'; const safeReturn = returnTo.includes('://') ? 'index.html' : returnTo;
  const client = configured && window.supabase ? window.supabase.createClient(window.FOCUS_SUPABASE_URL,window.FOCUS_SUPABASE_PUBLISHABLE_KEY) : null;
  function setMode(next) { mode=next; document.querySelectorAll('.tab').forEach(b => b.classList.toggle('active',b.dataset.mode===mode)); document.querySelector('.signup-only').hidden=mode!=='signup'; document.querySelector('#heading').textContent=mode==='signup'?'Create your account':'Welcome back'; document.querySelector('#sub').textContent=mode==='signup'?'Sync your focus across every device.':'Sign in to continue your focus journey.'; document.querySelector('#email-action').textContent=mode==='signup'?'Create account':'Sign in'; }
  document.querySelectorAll('.tab').forEach(b => b.onclick=() => setMode(b.dataset.mode)); document.querySelector('#guest').onclick=() => { localStorage.setItem('focusGuestMode','1'); location.assign(safeReturn); };
  document.querySelector('#email-action').onclick=async()=>{ if(!client){note.textContent='Supabase is not configured yet. Add its URL and publishable key first.';return;} const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value; if(!email||password.length<6){note.textContent='Enter an email and a password of at least 6 characters.';return;} if(mode==='signup'){const name=document.querySelector('#name').value.trim();const {error}=await client.auth.signUp({email,password,options:{data:{display_name:name},emailRedirectTo:new URL('profile.html',location.href).href}});note.textContent=error?error.message:'Check your email to confirm your account.';}else{const {error}=await client.auth.signInWithPassword({email,password});if(error){note.textContent=error.message;}else{location.assign(safeReturn);}}};
  document.querySelector('#google').onclick=async()=>{if(!client){note.textContent='Supabase is not configured yet.';return;}const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:new URL('profile.html',location.href).href}});if(error)note.textContent=error.message;};
  (async()=>{if(client){const {data:{session}}=await client.auth.getSession();if(session)location.replace(safeReturn);}})();
})();
